server:
  port: 34000
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: sa
    password: 123456
    virtual-host: /vvv/sit
  cloud:
    stream:
      bindings:
        testOutput:
          destination: exchange-fanout-888
          #          group: test-queue1
      rabbit:
        bindings:
          testOutput.producer:
            exchangeType: fanout